name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      PETSTORE_TEST_SUITE:
        description: 'Trigger the petstore selenium test workflow'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DEMO_USERNAME: ${{ secrets.DEMO_USERNAME }}
          DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}
        run: |
          python main.py

      - name: Archive HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: reports/test_report.html
